version: '3.9'

services:
  server:
    image: "nginx:stable-alpine"
    ports:
      - '8080:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
     
  php:
    build: 
      context: ./php
      dockerfile: dockerfile
    volumes:
      - ./src:/var/www/html
  mysql:
    image: 'mysql:latest'
    env_file:
      - ./env/mysql.conf
  composer:
    build: 
      context: ./composer
      dockerfile: dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm:
